### ISSUE TITLE
net.isIP is not a function  at new RedisClient

### ISSUE THREAD

**Issue by RemiFrontiere** [javilobo8/pubg-api-redis#10]
**Hi,I tried first to get data from the api with HTTP Request
**I work on TypeScript Ionic/Angular****

> ![image](https://user-images.githubusercontent.com/29545332/33735044-725085d2-db8e-11e7-8171-cecf59481722.png)

**But I got this error.**
> ![image](https://user-images.githubusercontent.com/29545332/33735067-8aad2194-db8e-11e7-82c6-1b1631b731f4.png)

 **So now I try to use pubg-api-redis but I have this error when I follow your README**

> import { PubgAPI, PubgAPIErrors, REGION, SEASON, MATCH } from 'pubg-api-redis';
> 
>      let api = new PubgAPI({
>        apikey: 'a16c7c6c-bdbexxxxxxxx-8206f380rd',
>        redisConfig: {
>          host: '127.0.0.1',
>          port: 6379,
>          expiration: 300, // Optional - defaults to 300.
>       },
>      });

![](https://cdn.discordapp.com/attachments/243060413628022784/388112861697802241/unknown.png)

**Comment by javilobo8** [comment]
Hi! This is not for frontend development, is for backend! You need to run with NodeJS

**Comment by RemiFrontiere** [comment]
Oups ! Ok thanks ;)
