### ISSUE TITLE
Unable to use Constants with webpack

### ISSUE THREAD

**Issue by ScottRocha** [javilobo8/pubg-api-redis#7]
Webpack fails with the following error:

ERROR in bundle.843ce3d5f317c15db433.js from UglifyJs
Name expected [./node_modules/pubg-api-redis/src/util/constants.js:1,0][bundle.843ce3d5f317c15db433.js:19419,6]

importing the constants the following two ways causes this:
import Constants from "pubg-api-redis/src/util/constants";
import { REGION, SEASON, MATCH } from "pubg-api-redis/src/util/constants";

importing the constants the following way causes more issues:
import { REGION, SEASON, MATCH } from "pubg-api-redis";

**Comment by javilobo8** [comment]
This module is for NodeJS engine, not for frontend.
